/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author tiago
 */
public class Agenda extends javax.swing.JFrame
{

    //https://youtu.be/8n_mkh8_GOA?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=343
    //final = significa que a referência nunca pode mudar, e não pode ser substituída em nenhuma das classes herdadas
    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda()
    {
        initComponents();

        //https://youtu.be/8n_mkh8_GOA?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=343
        controller = new AgendaController(this);

        //https://youtu.be/8n_mkh8_GOA?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=659
        iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jPanelCampos = new javax.swing.JPanel();
        TextId = new javax.swing.JTextField();
        jComboboxCliente = new javax.swing.JComboBox<>();
        jComboboxServico = new javax.swing.JComboBox<>();
        TextValor = new javax.swing.JTextField();
        TextFormatedData = new javax.swing.JFormattedTextField();
        TextFormatedHora = new javax.swing.JFormattedTextField();
        LabelHora = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        LabelServico = new javax.swing.JLabel();
        LabelCliente = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        jPanelObservacao = new javax.swing.JPanel();
        LabelObservacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        ButtonAgendar = new javax.swing.JButton();
        LabelAgenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCampos.setOpaque(false);
        jPanelCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextId.setEditable(false);
        TextId.setText("0");
        TextId.setToolTipText("");
        TextId.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextIdActionPerformed(evt);
            }
        });
        jPanelCampos.add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 280, 30));

        jPanelCampos.add(jComboboxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 280, 30));

        jComboboxServico.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jComboboxServicoItemStateChanged(evt);
            }
        });
        jPanelCampos.add(jComboboxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, 30));

        TextValor.setText("0");
        TextValor.setToolTipText("");
        TextValor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextValorActionPerformed(evt);
            }
        });
        jPanelCampos.add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 280, 30));

        TextFormatedData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanelCampos.add(TextFormatedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 280, 30));

        TextFormatedHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanelCampos.add(TextFormatedHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 280, 30));

        LabelHora.setForeground(new java.awt.Color(255, 255, 255));
        LabelHora.setText("Hora");
        jPanelCampos.add(LabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Data");
        jPanelCampos.add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        LabelValor.setForeground(new java.awt.Color(255, 255, 255));
        LabelValor.setText("Valor R$");
        jPanelCampos.add(LabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        LabelServico.setForeground(new java.awt.Color(255, 255, 255));
        LabelServico.setText("Servico");
        jPanelCampos.add(LabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        LabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        LabelCliente.setText("Cliente");
        jPanelCampos.add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        LabelId.setForeground(new java.awt.Color(255, 255, 255));
        LabelId.setText("Id");
        jPanelCampos.add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel3.add(jPanelCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 250));

        jPanelObservacao.setOpaque(false);
        jPanelObservacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        LabelObservacao.setText("Observação");
        jPanelObservacao.add(LabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TextObservacao.setColumns(20);
        TextObservacao.setRows(5);
        jScrollPane2.setViewportView(TextObservacao);

        jPanelObservacao.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, 140));

        ButtonAgendar.setBackground(new java.awt.Color(102, 255, 255));
        ButtonAgendar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar.setText("Agendar");
        ButtonAgendar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonAgendarActionPerformed(evt);
            }
        });
        jPanelObservacao.add(ButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 530, 50));

        jPanel3.add(jPanelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 550, 240));

        LabelAgenda.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        LabelAgenda.setForeground(new java.awt.Color(255, 255, 255));
        LabelAgenda.setText("Agenda");
        jPanel3.add(LabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 60));

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane1.setViewportView(TableAgendamentos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1170, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void ButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendarActionPerformed

      //https://youtu.be/RO-Y9J_0mD0?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=190
      this.controller.agendar();
      

    }//GEN-LAST:event_ButtonAgendarActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void jComboboxServicoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jComboboxServicoItemStateChanged
    {//GEN-HEADEREND:event_jComboboxServicoItemStateChanged
        //https://youtu.be/h66FfOpl2Tc?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=862
        this.controller.atualizaValor();

    }//GEN-LAST:event_jComboboxServicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendar;
    private javax.swing.JLabel LabelAgenda;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelServico;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JFormattedTextField TextFormatedData;
    private javax.swing.JFormattedTextField TextFormatedHora;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JComboBox<String> jComboboxCliente;
    private javax.swing.JComboBox<String> jComboboxServico;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCampos;
    private javax.swing.JPanel jPanelObservacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    //https://youtu.be/8n_mkh8_GOA?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=684
    /**
     * Chama o metodo do controller para atualizar a tabela e carregar os dados
     * na tela
     *
     * @param args the command line arguments
     */
    private void iniciar()
    {
        controller.atualizarTabela();

        //https://youtu.be/m406f4tGE-E?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=357
        this.controller.atualaizaCliente();

        //https://youtu.be/m406f4tGE-E?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=1234
        this.controller.atualaizaServico();

        //https://youtu.be/h66FfOpl2Tc?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=764
        this.controller.atualizaValor();

    }

    //https://youtu.be/8n_mkh8_GOA?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=1032
    public JTable getTableAgendamentos()
    {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos)
    {
        this.TableAgendamentos = TableAgendamentos;
    }

    //https://youtu.be/m406f4tGE-E?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=474
    public JComboBox<String> getjComboboxCliente()
    {
        return jComboboxCliente;
    }

    public void setjComboboxCliente(JComboBox<String> jComboboxCliente)
    {
        this.jComboboxCliente = jComboboxCliente;
    }

    public JComboBox<String> getjComboboxServico()
    {
        return jComboboxServico;
    }

    public void setjComboboxServico(JComboBox<String> jComboboxServico)
    {
        this.jComboboxServico = jComboboxServico;
    }

    //https://youtu.be/h66FfOpl2Tc?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=599
    public JTextField getTextValor()
    {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor)
    {
        this.TextValor = TextValor;
    }

    
   //https://youtu.be/6wSls9HHmbw?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=420 
    public JFormattedTextField getTextFormatedData()
    {
        return TextFormatedData;
    }

    public void setTextFormatedData(JFormattedTextField TextFormatedData)
    {
        this.TextFormatedData = TextFormatedData;
    }

    public JFormattedTextField getTextFormatedHora()
    {
        return TextFormatedHora;
    }

    public void setTextFormatedHora(JFormattedTextField TextFormatedHora)
    {
        this.TextFormatedHora = TextFormatedHora;
    }

    public JTextField getTextId()
    {
        return TextId;
    }

    public void setTextId(JTextField TextId)
    {
        this.TextId = TextId;
    }

    public JTextArea getTextObservacao()
    {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao)
    {
        this.TextObservacao = TextObservacao;
    }
    
    

}
