/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LogInController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tiago
 */
public class Login extends javax.swing.JFrame {

    private final LogInController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        //https://youtu.be/flKEjGROQ1o?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=648
        controller = new LogInController(this);
        
        //https://youtu.be/vV6ENkfLo1s?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=622
        //Simular uma conexao com o banco
        Banco.inicia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        LabelTituloLogin = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        LabelSenha = new javax.swing.JLabel();
        TextSenha = new javax.swing.JPasswordField();
        ButtonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTituloLogin.setFont(new java.awt.Font("Courier 10 Pitch", 1, 48)); // NOI18N
        LabelTituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelTituloLogin.setText("Login");
        jPanel1.add(LabelTituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        LabelUsuario.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario");
        jPanel1.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        TextUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 40));

        LabelSenha.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        LabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        LabelSenha.setText("Senha");
        jPanel1.add(LabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        TextSenha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 400, 40));

        ButtonEntrar.setBackground(new java.awt.Color(164, 152, 152));
        ButtonEntrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ButtonEntrar.setText("Entrar");
        ButtonEntrar.setActionCommand("ButtonEntrar");
        ButtonEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 400, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void ButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntrarActionPerformed
       //Metoa executa ao clicar:
       //https://youtu.be/flKEjGROQ1o?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=756
       //this.controller.fizTarefa();
           
       
       //https://youtu.be/flKEjGROQ1o?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=1255
        System.out.println(TextUsuario.getText());//Pega o usuario
        System.out.println(TextSenha.getText());  //Pega a senha
        
        //https://youtu.be/vV6ENkfLo1s?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=1108
        this.controller.entrarNoSistema();
        
        
        
       
       
    }//GEN-LAST:event_ButtonEntrarActionPerformed

    private void TextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEntrar;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelTituloLogin;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    public void exibeMensagem(String mensagem)
    {
        //https://youtu.be/flKEjGROQ1o?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=456
        JOptionPane.showMessageDialog(null, mensagem);
    }

    //https://youtu.be/flKEjGROQ1o?list=PLJIP7GdByOyuBKB--fIO2DoQaPVXm9lCw&t=1517
    public JPasswordField getTextSenha()
    {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha)
    {
        this.TextSenha = TextSenha;
    }

    public JTextField getTextUsuario()
    {
        return TextUsuario;
    }

    public void setTextUsuario(JTextField TextUsuario)
    {
        this.TextUsuario = TextUsuario;
    }
    
    
}
